export const data = [
    {
        id: 1,
        name: 'John Doe',
        email: 'john.doe@example.com',
        phone: '9876543210',
        query: 'Admission process details',
        category: 'Admissions',
        comments: 'Looking for detailed guidance on the admission timeline.',
        date: '2024-12-10',
        status: 'Pending',
    },
    {
        id: 2,
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '9123456789',
        query: 'Fee structure for BCA',
        category: 'Fee Inquiry',
        comments: 'Please provide semester-wise fee details.',
        date: '2024-12-11',
        status: 'Resolved',
    },
    {
        id: 3,
        name: 'Rahul Yadav',
        email: 'rahul.yadav@example.com',
        phone: '9988776655',
        query: 'Scholarship eligibility',
        category: 'Scholarships',
        comments: 'Need information about scholarship criteria for BCA.',
        date: '2024-12-12',
        status: 'Pending',
    },
    {
        id: 4,
        name: 'Neha Singh',
        email: 'neha.singh@example.com',
        phone: '8877665544',
        query: 'Hostel availability',
        category: 'Hostel',
        comments: 'Is the hostel facility available for female students?',
        date: '2024-12-13',
        status: 'Resolved',
    },
    {
        id: 1,
        name: 'John Doe',
        email: 'john.doe@example.com',
        phone: '9876543210',
        query: 'Admission process details',
        category: 'Admissions',
        comments: 'Looking for detailed guidance on the admission timeline.',
        date: '2024-12-10',
        status: 'Pending',
    },
    {
        id: 2,
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '9123456789',
        query: 'Fee structure for BCA',
        category: 'Fee Inquiry',
        comments: 'Please provide semester-wise fee details.',
        date: '2024-12-11',
        status: 'Resolved',
    },
    {
        id: 3,
        name: 'Rahul Yadav',
        email: 'rahul.yadav@example.com',
        phone: '9988776655',
        query: 'Scholarship eligibility',
        category: 'Scholarships',
        comments: 'Need information about scholarship criteria for BCA.',
        date: '2024-12-12',
        status: 'Pending',
    },
    {
        id: 4,
        name: 'Neha Singh',
        email: 'neha.singh@example.com',
        phone: '8877665544',
        query: 'Hostel availability',
        category: 'Hostel',
        comments: 'Is the hostel facility available for female students?',
        date: '2024-12-13',
        status: 'Resolved',
    },
]